package com.dynastech.system.entity;

import java.util.Date;
import java.util.List;

public class User {

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column RS_User.Id
	 * @mbggenerated  Wed Jul 26 18:19:56 CST 2017
	 */
	private String id;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column RS_User.AccountName
	 * @mbggenerated  Wed Jul 26 18:19:56 CST 2017
	 */
	private String accountname;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column RS_User.Birthday
	 * @mbggenerated  Wed Jul 26 18:19:56 CST 2017
	 */
	private Date birthday;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column RS_User.DateTimeCreated
	 * @mbggenerated  Wed Jul 26 18:19:56 CST 2017
	 */
	private Date datetimecreated;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column RS_User.DateTimeModified
	 * @mbggenerated  Wed Jul 26 18:19:56 CST 2017
	 */
	private Date datetimemodified;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column RS_User.Description
	 * @mbggenerated  Wed Jul 26 18:19:56 CST 2017
	 */
	private String description;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column RS_User.DisplayName
	 * @mbggenerated  Wed Jul 26 18:19:56 CST 2017
	 */
	private String displayname;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column RS_User.ExtensionData
	 * @mbggenerated  Wed Jul 26 18:19:56 CST 2017
	 */
	private String extensiondata;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column RS_User.FirstName
	 * @mbggenerated  Wed Jul 26 18:19:56 CST 2017
	 */
	private String firstname;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column RS_User.IdNumber
	 * @mbggenerated  Wed Jul 26 18:19:56 CST 2017
	 */
	private String idnumber;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column RS_User.IsDeleted
	 * @mbggenerated  Wed Jul 26 18:19:56 CST 2017
	 */
	private Boolean isdeleted;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column RS_User.IsEnabled
	 * @mbggenerated  Wed Jul 26 18:19:56 CST 2017
	 */
	private Boolean isenabled;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column RS_User.LastName
	 * @mbggenerated  Wed Jul 26 18:19:56 CST 2017
	 */
	private String lastname;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column RS_User.MiddleName
	 * @mbggenerated  Wed Jul 26 18:19:56 CST 2017
	 */
	private String middlename;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column RS_User.Name
	 * @mbggenerated  Wed Jul 26 18:19:56 CST 2017
	 */
	private String name;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column RS_User.Sex
	 * @mbggenerated  Wed Jul 26 18:19:56 CST 2017
	 */
	private Integer sex;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column RS_User.Sn
	 * @mbggenerated  Wed Jul 26 18:19:56 CST 2017
	 */
	private Integer sn;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column RS_User.Type
	 * @mbggenerated  Wed Jul 26 18:19:56 CST 2017
	 */
	private String type;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column RS_User.WorkNumber
	 * @mbggenerated  Wed Jul 26 18:19:56 CST 2017
	 */
	private String worknumber;

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column RS_User.Id
	 * @return  the value of RS_User.Id
	 * @mbggenerated  Wed Jul 26 18:19:56 CST 2017
	 */
	
	//用户所在的组织
	private List<Organization> orgs;
	
	public List<Organization> getOrgs() {
		return orgs;
	}
	
	public void setOrgs(List<Organization> orgs) {
		this.orgs = orgs;
	}
	
	public String getId() {
		return id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column RS_User.Id
	 * @param id  the value for RS_User.Id
	 * @mbggenerated  Wed Jul 26 18:19:56 CST 2017
	 */
	public void setId(String id) {
		this.id = id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column RS_User.AccountName
	 * @return  the value of RS_User.AccountName
	 * @mbggenerated  Wed Jul 26 18:19:56 CST 2017
	 */
	public String getAccountname() {
		return accountname;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column RS_User.AccountName
	 * @param accountname  the value for RS_User.AccountName
	 * @mbggenerated  Wed Jul 26 18:19:56 CST 2017
	 */
	public void setAccountname(String accountname) {
		this.accountname = accountname;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column RS_User.Birthday
	 * @return  the value of RS_User.Birthday
	 * @mbggenerated  Wed Jul 26 18:19:56 CST 2017
	 */
	public Date getBirthday() {
		return birthday;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column RS_User.Birthday
	 * @param birthday  the value for RS_User.Birthday
	 * @mbggenerated  Wed Jul 26 18:19:56 CST 2017
	 */
	public void setBirthday(Date birthday) {
		this.birthday = birthday;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column RS_User.DateTimeCreated
	 * @return  the value of RS_User.DateTimeCreated
	 * @mbggenerated  Wed Jul 26 18:19:56 CST 2017
	 */
	public Date getDatetimecreated() {
		return datetimecreated;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column RS_User.DateTimeCreated
	 * @param datetimecreated  the value for RS_User.DateTimeCreated
	 * @mbggenerated  Wed Jul 26 18:19:56 CST 2017
	 */
	public void setDatetimecreated(Date datetimecreated) {
		this.datetimecreated = datetimecreated;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column RS_User.DateTimeModified
	 * @return  the value of RS_User.DateTimeModified
	 * @mbggenerated  Wed Jul 26 18:19:56 CST 2017
	 */
	public Date getDatetimemodified() {
		return datetimemodified;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column RS_User.DateTimeModified
	 * @param datetimemodified  the value for RS_User.DateTimeModified
	 * @mbggenerated  Wed Jul 26 18:19:56 CST 2017
	 */
	public void setDatetimemodified(Date datetimemodified) {
		this.datetimemodified = datetimemodified;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column RS_User.Description
	 * @return  the value of RS_User.Description
	 * @mbggenerated  Wed Jul 26 18:19:56 CST 2017
	 */
	public String getDescription() {
		return description;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column RS_User.Description
	 * @param description  the value for RS_User.Description
	 * @mbggenerated  Wed Jul 26 18:19:56 CST 2017
	 */
	public void setDescription(String description) {
		this.description = description;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column RS_User.DisplayName
	 * @return  the value of RS_User.DisplayName
	 * @mbggenerated  Wed Jul 26 18:19:56 CST 2017
	 */
	public String getDisplayname() {
		return displayname;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column RS_User.DisplayName
	 * @param displayname  the value for RS_User.DisplayName
	 * @mbggenerated  Wed Jul 26 18:19:56 CST 2017
	 */
	public void setDisplayname(String displayname) {
		this.displayname = displayname;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column RS_User.ExtensionData
	 * @return  the value of RS_User.ExtensionData
	 * @mbggenerated  Wed Jul 26 18:19:56 CST 2017
	 */
	public String getExtensiondata() {
		return extensiondata;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column RS_User.ExtensionData
	 * @param extensiondata  the value for RS_User.ExtensionData
	 * @mbggenerated  Wed Jul 26 18:19:56 CST 2017
	 */
	public void setExtensiondata(String extensiondata) {
		this.extensiondata = extensiondata;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column RS_User.FirstName
	 * @return  the value of RS_User.FirstName
	 * @mbggenerated  Wed Jul 26 18:19:56 CST 2017
	 */
	public String getFirstname() {
		return firstname;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column RS_User.FirstName
	 * @param firstname  the value for RS_User.FirstName
	 * @mbggenerated  Wed Jul 26 18:19:56 CST 2017
	 */
	public void setFirstname(String firstname) {
		this.firstname = firstname;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column RS_User.IdNumber
	 * @return  the value of RS_User.IdNumber
	 * @mbggenerated  Wed Jul 26 18:19:56 CST 2017
	 */
	public String getIdnumber() {
		return idnumber;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column RS_User.IdNumber
	 * @param idnumber  the value for RS_User.IdNumber
	 * @mbggenerated  Wed Jul 26 18:19:56 CST 2017
	 */
	public void setIdnumber(String idnumber) {
		this.idnumber = idnumber;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column RS_User.IsDeleted
	 * @return  the value of RS_User.IsDeleted
	 * @mbggenerated  Wed Jul 26 18:19:56 CST 2017
	 */
	public Boolean getIsdeleted() {
		return isdeleted;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column RS_User.IsDeleted
	 * @param isdeleted  the value for RS_User.IsDeleted
	 * @mbggenerated  Wed Jul 26 18:19:56 CST 2017
	 */
	public void setIsdeleted(Boolean isdeleted) {
		this.isdeleted = isdeleted;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column RS_User.IsEnabled
	 * @return  the value of RS_User.IsEnabled
	 * @mbggenerated  Wed Jul 26 18:19:56 CST 2017
	 */
	public Boolean getIsenabled() {
		return isenabled;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column RS_User.IsEnabled
	 * @param isenabled  the value for RS_User.IsEnabled
	 * @mbggenerated  Wed Jul 26 18:19:56 CST 2017
	 */
	public void setIsenabled(Boolean isenabled) {
		this.isenabled = isenabled;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column RS_User.LastName
	 * @return  the value of RS_User.LastName
	 * @mbggenerated  Wed Jul 26 18:19:56 CST 2017
	 */
	public String getLastname() {
		return lastname;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column RS_User.LastName
	 * @param lastname  the value for RS_User.LastName
	 * @mbggenerated  Wed Jul 26 18:19:56 CST 2017
	 */
	public void setLastname(String lastname) {
		this.lastname = lastname;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column RS_User.MiddleName
	 * @return  the value of RS_User.MiddleName
	 * @mbggenerated  Wed Jul 26 18:19:56 CST 2017
	 */
	public String getMiddlename() {
		return middlename;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column RS_User.MiddleName
	 * @param middlename  the value for RS_User.MiddleName
	 * @mbggenerated  Wed Jul 26 18:19:56 CST 2017
	 */
	public void setMiddlename(String middlename) {
		this.middlename = middlename;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column RS_User.Name
	 * @return  the value of RS_User.Name
	 * @mbggenerated  Wed Jul 26 18:19:56 CST 2017
	 */
	public String getName() {
		return name;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column RS_User.Name
	 * @param name  the value for RS_User.Name
	 * @mbggenerated  Wed Jul 26 18:19:56 CST 2017
	 */
	public void setName(String name) {
		this.name = name;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column RS_User.Sex
	 * @return  the value of RS_User.Sex
	 * @mbggenerated  Wed Jul 26 18:19:56 CST 2017
	 */
	public Integer getSex() {
		return sex;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column RS_User.Sex
	 * @param sex  the value for RS_User.Sex
	 * @mbggenerated  Wed Jul 26 18:19:56 CST 2017
	 */
	public void setSex(Integer sex) {
		this.sex = sex;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column RS_User.Sn
	 * @return  the value of RS_User.Sn
	 * @mbggenerated  Wed Jul 26 18:19:56 CST 2017
	 */
	public Integer getSn() {
		return sn;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column RS_User.Sn
	 * @param sn  the value for RS_User.Sn
	 * @mbggenerated  Wed Jul 26 18:19:56 CST 2017
	 */
	public void setSn(Integer sn) {
		this.sn = sn;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column RS_User.Type
	 * @return  the value of RS_User.Type
	 * @mbggenerated  Wed Jul 26 18:19:56 CST 2017
	 */
	public String getType() {
		return type;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column RS_User.Type
	 * @param type  the value for RS_User.Type
	 * @mbggenerated  Wed Jul 26 18:19:56 CST 2017
	 */
	public void setType(String type) {
		this.type = type;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column RS_User.WorkNumber
	 * @return  the value of RS_User.WorkNumber
	 * @mbggenerated  Wed Jul 26 18:19:56 CST 2017
	 */
	public String getWorknumber() {
		return worknumber;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column RS_User.WorkNumber
	 * @param worknumber  the value for RS_User.WorkNumber
	 * @mbggenerated  Wed Jul 26 18:19:56 CST 2017
	 */
	public void setWorknumber(String worknumber) {
		this.worknumber = worknumber;
	}

	@Override
	public String toString() {
		return "User [id=" + id + ", accountname=" + accountname + ", birthday=" + birthday + ", datetimecreated="
				+ datetimecreated + ", datetimemodified=" + datetimemodified + ", description=" + description
				+ ", displayname=" + displayname + ", extensiondata=" + extensiondata + ", firstname=" + firstname
				+ ", idnumber=" + idnumber + ", isdeleted=" + isdeleted + ", isenabled=" + isenabled + ", lastname="
				+ lastname + ", middlename=" + middlename + ", name=" + name + ", sex=" + sex + ", sn=" + sn + ", type="
				+ type + ", worknumber=" + worknumber + "]";
	}
}