package com.dynastech.system.entity;

import java.util.ArrayList;
import java.util.Date;
import java.util.List;

public class UserExample {
    /**
	 * This field was generated by MyBatis Generator. This field corresponds to the database table RS_User
	 * @mbggenerated  Wed Jul 26 18:19:56 CST 2017
	 */
	protected String orderByClause;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database table RS_User
	 * @mbggenerated  Wed Jul 26 18:19:56 CST 2017
	 */
	protected boolean distinct;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database table RS_User
	 * @mbggenerated  Wed Jul 26 18:19:56 CST 2017
	 */
	protected List<Criteria> oredCriteria;

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table RS_User
	 * @mbggenerated  Wed Jul 26 18:19:56 CST 2017
	 */
	public UserExample() {
		oredCriteria = new ArrayList<Criteria>();
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table RS_User
	 * @mbggenerated  Wed Jul 26 18:19:56 CST 2017
	 */
	public void setOrderByClause(String orderByClause) {
		this.orderByClause = orderByClause;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table RS_User
	 * @mbggenerated  Wed Jul 26 18:19:56 CST 2017
	 */
	public String getOrderByClause() {
		return orderByClause;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table RS_User
	 * @mbggenerated  Wed Jul 26 18:19:56 CST 2017
	 */
	public void setDistinct(boolean distinct) {
		this.distinct = distinct;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table RS_User
	 * @mbggenerated  Wed Jul 26 18:19:56 CST 2017
	 */
	public boolean isDistinct() {
		return distinct;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table RS_User
	 * @mbggenerated  Wed Jul 26 18:19:56 CST 2017
	 */
	public List<Criteria> getOredCriteria() {
		return oredCriteria;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table RS_User
	 * @mbggenerated  Wed Jul 26 18:19:56 CST 2017
	 */
	public void or(Criteria criteria) {
		oredCriteria.add(criteria);
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table RS_User
	 * @mbggenerated  Wed Jul 26 18:19:56 CST 2017
	 */
	public Criteria or() {
		Criteria criteria = createCriteriaInternal();
		oredCriteria.add(criteria);
		return criteria;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table RS_User
	 * @mbggenerated  Wed Jul 26 18:19:56 CST 2017
	 */
	public Criteria createCriteria() {
		Criteria criteria = createCriteriaInternal();
		if (oredCriteria.size() == 0) {
			oredCriteria.add(criteria);
		}
		return criteria;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table RS_User
	 * @mbggenerated  Wed Jul 26 18:19:56 CST 2017
	 */
	protected Criteria createCriteriaInternal() {
		Criteria criteria = new Criteria();
		return criteria;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table RS_User
	 * @mbggenerated  Wed Jul 26 18:19:56 CST 2017
	 */
	public void clear() {
		oredCriteria.clear();
		orderByClause = null;
		distinct = false;
	}

	/**
	 * This class was generated by MyBatis Generator. This class corresponds to the database table RS_User
	 * @mbggenerated  Wed Jul 26 18:19:56 CST 2017
	 */
	protected abstract static class GeneratedCriteria {
		protected List<Criterion> criteria;

		protected GeneratedCriteria() {
			super();
			criteria = new ArrayList<Criterion>();
		}

		public boolean isValid() {
			return criteria.size() > 0;
		}

		public List<Criterion> getAllCriteria() {
			return criteria;
		}

		public List<Criterion> getCriteria() {
			return criteria;
		}

		protected void addCriterion(String condition) {
			if (condition == null) {
				throw new RuntimeException("Value for condition cannot be null");
			}
			criteria.add(new Criterion(condition));
		}

		protected void addCriterion(String condition, Object value, String property) {
			if (value == null) {
				throw new RuntimeException("Value for " + property + " cannot be null");
			}
			criteria.add(new Criterion(condition, value));
		}

		protected void addCriterion(String condition, Object value1, Object value2, String property) {
			if (value1 == null || value2 == null) {
				throw new RuntimeException("Between values for " + property + " cannot be null");
			}
			criteria.add(new Criterion(condition, value1, value2));
		}

		public Criteria andIdIsNull() {
			addCriterion("u.Id is null");
			return (Criteria) this;
		}

		public Criteria andIdIsNotNull() {
			addCriterion("u.Id is not null");
			return (Criteria) this;
		}

		public Criteria andIdEqualTo(String value) {
			addCriterion("u.Id =", value, "id");
			return (Criteria) this;
		}

		public Criteria andIdNotEqualTo(String value) {
			addCriterion("u.Id <>", value, "id");
			return (Criteria) this;
		}

		public Criteria andIdGreaterThan(String value) {
			addCriterion("u.Id >", value, "id");
			return (Criteria) this;
		}

		public Criteria andIdGreaterThanOrEqualTo(String value) {
			addCriterion("u.Id >=", value, "id");
			return (Criteria) this;
		}

		public Criteria andIdLessThan(String value) {
			addCriterion("u.Id <", value, "id");
			return (Criteria) this;
		}

		public Criteria andIdLessThanOrEqualTo(String value) {
			addCriterion("u.Id <=", value, "id");
			return (Criteria) this;
		}

		public Criteria andIdLike(String value) {
			addCriterion("u.Id like", value, "id");
			return (Criteria) this;
		}

		public Criteria andIdNotLike(String value) {
			addCriterion("u.Id not like", value, "id");
			return (Criteria) this;
		}

		public Criteria andIdIn(List<String> values) {
			addCriterion("u.Id in", values, "id");
			return (Criteria) this;
		}

		public Criteria andIdNotIn(List<String> values) {
			addCriterion("u.Id not in", values, "id");
			return (Criteria) this;
		}

		public Criteria andIdBetween(String value1, String value2) {
			addCriterion("u.Id between", value1, value2, "id");
			return (Criteria) this;
		}

		public Criteria andIdNotBetween(String value1, String value2) {
			addCriterion("u.Id not between", value1, value2, "id");
			return (Criteria) this;
		}

		public Criteria andAccountnameIsNull() {
			addCriterion("u.AccountName is null");
			return (Criteria) this;
		}

		public Criteria andAccountnameIsNotNull() {
			addCriterion("u.AccountName is not null");
			return (Criteria) this;
		}

		public Criteria andAccountnameEqualTo(String value) {
			addCriterion("u.AccountName =", value, "accountname");
			return (Criteria) this;
		}

		public Criteria andAccountnameNotEqualTo(String value) {
			addCriterion("u.AccountName <>", value, "accountname");
			return (Criteria) this;
		}

		public Criteria andAccountnameGreaterThan(String value) {
			addCriterion("u.AccountName >", value, "accountname");
			return (Criteria) this;
		}

		public Criteria andAccountnameGreaterThanOrEqualTo(String value) {
			addCriterion("u.AccountName >=", value, "accountname");
			return (Criteria) this;
		}

		public Criteria andAccountnameLessThan(String value) {
			addCriterion("u.AccountName <", value, "accountname");
			return (Criteria) this;
		}

		public Criteria andAccountnameLessThanOrEqualTo(String value) {
			addCriterion("u.AccountName <=", value, "accountname");
			return (Criteria) this;
		}

		public Criteria andAccountnameLike(String value) {
			addCriterion("u.AccountName like", value, "accountname");
			return (Criteria) this;
		}

		public Criteria andAccountnameNotLike(String value) {
			addCriterion("u.AccountName not like", value, "accountname");
			return (Criteria) this;
		}

		public Criteria andAccountnameIn(List<String> values) {
			addCriterion("u.AccountName in", values, "accountname");
			return (Criteria) this;
		}

		public Criteria andAccountnameNotIn(List<String> values) {
			addCriterion("u.AccountName not in", values, "accountname");
			return (Criteria) this;
		}

		public Criteria andAccountnameBetween(String value1, String value2) {
			addCriterion("u.AccountName between", value1, value2, "accountname");
			return (Criteria) this;
		}

		public Criteria andAccountnameNotBetween(String value1, String value2) {
			addCriterion("u.AccountName not between", value1, value2, "accountname");
			return (Criteria) this;
		}

		public Criteria andBirthdayIsNull() {
			addCriterion("u.Birthday is null");
			return (Criteria) this;
		}

		public Criteria andBirthdayIsNotNull() {
			addCriterion("u.Birthday is not null");
			return (Criteria) this;
		}

		public Criteria andBirthdayEqualTo(Date value) {
			addCriterion("u.Birthday =", value, "birthday");
			return (Criteria) this;
		}

		public Criteria andBirthdayNotEqualTo(Date value) {
			addCriterion("u.Birthday <>", value, "birthday");
			return (Criteria) this;
		}

		public Criteria andBirthdayGreaterThan(Date value) {
			addCriterion("u.Birthday >", value, "birthday");
			return (Criteria) this;
		}

		public Criteria andBirthdayGreaterThanOrEqualTo(Date value) {
			addCriterion("u.Birthday >=", value, "birthday");
			return (Criteria) this;
		}

		public Criteria andBirthdayLessThan(Date value) {
			addCriterion("u.Birthday <", value, "birthday");
			return (Criteria) this;
		}

		public Criteria andBirthdayLessThanOrEqualTo(Date value) {
			addCriterion("u.Birthday <=", value, "birthday");
			return (Criteria) this;
		}

		public Criteria andBirthdayIn(List<Date> values) {
			addCriterion("u.Birthday in", values, "birthday");
			return (Criteria) this;
		}

		public Criteria andBirthdayNotIn(List<Date> values) {
			addCriterion("u.Birthday not in", values, "birthday");
			return (Criteria) this;
		}

		public Criteria andBirthdayBetween(Date value1, Date value2) {
			addCriterion("u.Birthday between", value1, value2, "birthday");
			return (Criteria) this;
		}

		public Criteria andBirthdayNotBetween(Date value1, Date value2) {
			addCriterion("u.Birthday not between", value1, value2, "birthday");
			return (Criteria) this;
		}

		public Criteria andDatetimecreatedIsNull() {
			addCriterion("u.DateTimeCreated is null");
			return (Criteria) this;
		}

		public Criteria andDatetimecreatedIsNotNull() {
			addCriterion("u.DateTimeCreated is not null");
			return (Criteria) this;
		}

		public Criteria andDatetimecreatedEqualTo(Date value) {
			addCriterion("u.DateTimeCreated =", value, "datetimecreated");
			return (Criteria) this;
		}

		public Criteria andDatetimecreatedNotEqualTo(Date value) {
			addCriterion("u.DateTimeCreated <>", value, "datetimecreated");
			return (Criteria) this;
		}

		public Criteria andDatetimecreatedGreaterThan(Date value) {
			addCriterion("u.DateTimeCreated >", value, "datetimecreated");
			return (Criteria) this;
		}

		public Criteria andDatetimecreatedGreaterThanOrEqualTo(Date value) {
			addCriterion("u.DateTimeCreated >=", value, "datetimecreated");
			return (Criteria) this;
		}

		public Criteria andDatetimecreatedLessThan(Date value) {
			addCriterion("u.DateTimeCreated <", value, "datetimecreated");
			return (Criteria) this;
		}

		public Criteria andDatetimecreatedLessThanOrEqualTo(Date value) {
			addCriterion("u.DateTimeCreated <=", value, "datetimecreated");
			return (Criteria) this;
		}

		public Criteria andDatetimecreatedIn(List<Date> values) {
			addCriterion("u.DateTimeCreated in", values, "datetimecreated");
			return (Criteria) this;
		}

		public Criteria andDatetimecreatedNotIn(List<Date> values) {
			addCriterion("u.DateTimeCreated not in", values, "datetimecreated");
			return (Criteria) this;
		}

		public Criteria andDatetimecreatedBetween(Date value1, Date value2) {
			addCriterion("u.DateTimeCreated between", value1, value2, "datetimecreated");
			return (Criteria) this;
		}

		public Criteria andDatetimecreatedNotBetween(Date value1, Date value2) {
			addCriterion("u.DateTimeCreated not between", value1, value2, "datetimecreated");
			return (Criteria) this;
		}

		public Criteria andDatetimemodifiedIsNull() {
			addCriterion("u.DateTimeModified is null");
			return (Criteria) this;
		}

		public Criteria andDatetimemodifiedIsNotNull() {
			addCriterion("u.DateTimeModified is not null");
			return (Criteria) this;
		}

		public Criteria andDatetimemodifiedEqualTo(Date value) {
			addCriterion("u.DateTimeModified =", value, "datetimemodified");
			return (Criteria) this;
		}

		public Criteria andDatetimemodifiedNotEqualTo(Date value) {
			addCriterion("u.DateTimeModified <>", value, "datetimemodified");
			return (Criteria) this;
		}

		public Criteria andDatetimemodifiedGreaterThan(Date value) {
			addCriterion("u.DateTimeModified >", value, "datetimemodified");
			return (Criteria) this;
		}

		public Criteria andDatetimemodifiedGreaterThanOrEqualTo(Date value) {
			addCriterion("u.DateTimeModified >=", value, "datetimemodified");
			return (Criteria) this;
		}

		public Criteria andDatetimemodifiedLessThan(Date value) {
			addCriterion("u.DateTimeModified <", value, "datetimemodified");
			return (Criteria) this;
		}

		public Criteria andDatetimemodifiedLessThanOrEqualTo(Date value) {
			addCriterion("u.DateTimeModified <=", value, "datetimemodified");
			return (Criteria) this;
		}

		public Criteria andDatetimemodifiedIn(List<Date> values) {
			addCriterion("u.DateTimeModified in", values, "datetimemodified");
			return (Criteria) this;
		}

		public Criteria andDatetimemodifiedNotIn(List<Date> values) {
			addCriterion("u.DateTimeModified not in", values, "datetimemodified");
			return (Criteria) this;
		}

		public Criteria andDatetimemodifiedBetween(Date value1, Date value2) {
			addCriterion("u.DateTimeModified between", value1, value2, "datetimemodified");
			return (Criteria) this;
		}

		public Criteria andDatetimemodifiedNotBetween(Date value1, Date value2) {
			addCriterion("u.DateTimeModified not between", value1, value2, "datetimemodified");
			return (Criteria) this;
		}

		public Criteria andDescriptionIsNull() {
			addCriterion("u.Description is null");
			return (Criteria) this;
		}

		public Criteria andDescriptionIsNotNull() {
			addCriterion("u.Description is not null");
			return (Criteria) this;
		}

		public Criteria andDescriptionEqualTo(String value) {
			addCriterion("u.Description =", value, "description");
			return (Criteria) this;
		}

		public Criteria andDescriptionNotEqualTo(String value) {
			addCriterion("u.Description <>", value, "description");
			return (Criteria) this;
		}

		public Criteria andDescriptionGreaterThan(String value) {
			addCriterion("u.Description >", value, "description");
			return (Criteria) this;
		}

		public Criteria andDescriptionGreaterThanOrEqualTo(String value) {
			addCriterion("u.Description >=", value, "description");
			return (Criteria) this;
		}

		public Criteria andDescriptionLessThan(String value) {
			addCriterion("u.Description <", value, "description");
			return (Criteria) this;
		}

		public Criteria andDescriptionLessThanOrEqualTo(String value) {
			addCriterion("u.Description <=", value, "description");
			return (Criteria) this;
		}

		public Criteria andDescriptionLike(String value) {
			addCriterion("u.Description like", value, "description");
			return (Criteria) this;
		}

		public Criteria andDescriptionNotLike(String value) {
			addCriterion("u.Description not like", value, "description");
			return (Criteria) this;
		}

		public Criteria andDescriptionIn(List<String> values) {
			addCriterion("u.Description in", values, "description");
			return (Criteria) this;
		}

		public Criteria andDescriptionNotIn(List<String> values) {
			addCriterion("u.Description not in", values, "description");
			return (Criteria) this;
		}

		public Criteria andDescriptionBetween(String value1, String value2) {
			addCriterion("u.Description between", value1, value2, "description");
			return (Criteria) this;
		}

		public Criteria andDescriptionNotBetween(String value1, String value2) {
			addCriterion("u.Description not between", value1, value2, "description");
			return (Criteria) this;
		}

		public Criteria andDisplaynameIsNull() {
			addCriterion("u.DisplayName is null");
			return (Criteria) this;
		}

		public Criteria andDisplaynameIsNotNull() {
			addCriterion("u.DisplayName is not null");
			return (Criteria) this;
		}

		public Criteria andDisplaynameEqualTo(String value) {
			addCriterion("u.DisplayName =", value, "displayname");
			return (Criteria) this;
		}

		public Criteria andDisplaynameNotEqualTo(String value) {
			addCriterion("u.DisplayName <>", value, "displayname");
			return (Criteria) this;
		}

		public Criteria andDisplaynameGreaterThan(String value) {
			addCriterion("u.DisplayName >", value, "displayname");
			return (Criteria) this;
		}

		public Criteria andDisplaynameGreaterThanOrEqualTo(String value) {
			addCriterion("u.DisplayName >=", value, "displayname");
			return (Criteria) this;
		}

		public Criteria andDisplaynameLessThan(String value) {
			addCriterion("u.DisplayName <", value, "displayname");
			return (Criteria) this;
		}

		public Criteria andDisplaynameLessThanOrEqualTo(String value) {
			addCriterion("u.DisplayName <=", value, "displayname");
			return (Criteria) this;
		}

		public Criteria andDisplaynameLike(String value) {
			addCriterion("u.DisplayName like", value, "displayname");
			return (Criteria) this;
		}

		public Criteria andDisplaynameNotLike(String value) {
			addCriterion("u.DisplayName not like", value, "displayname");
			return (Criteria) this;
		}

		public Criteria andDisplaynameIn(List<String> values) {
			addCriterion("u.DisplayName in", values, "displayname");
			return (Criteria) this;
		}

		public Criteria andDisplaynameNotIn(List<String> values) {
			addCriterion("u.DisplayName not in", values, "displayname");
			return (Criteria) this;
		}

		public Criteria andDisplaynameBetween(String value1, String value2) {
			addCriterion("u.DisplayName between", value1, value2, "displayname");
			return (Criteria) this;
		}

		public Criteria andDisplaynameNotBetween(String value1, String value2) {
			addCriterion("u.DisplayName not between", value1, value2, "displayname");
			return (Criteria) this;
		}

		public Criteria andExtensiondataIsNull() {
			addCriterion("u.ExtensionData is null");
			return (Criteria) this;
		}

		public Criteria andExtensiondataIsNotNull() {
			addCriterion("u.ExtensionData is not null");
			return (Criteria) this;
		}

		public Criteria andExtensiondataEqualTo(String value) {
			addCriterion("u.ExtensionData =", value, "extensiondata");
			return (Criteria) this;
		}

		public Criteria andExtensiondataNotEqualTo(String value) {
			addCriterion("u.ExtensionData <>", value, "extensiondata");
			return (Criteria) this;
		}

		public Criteria andExtensiondataGreaterThan(String value) {
			addCriterion("u.ExtensionData >", value, "extensiondata");
			return (Criteria) this;
		}

		public Criteria andExtensiondataGreaterThanOrEqualTo(String value) {
			addCriterion("u.ExtensionData >=", value, "extensiondata");
			return (Criteria) this;
		}

		public Criteria andExtensiondataLessThan(String value) {
			addCriterion("u.ExtensionData <", value, "extensiondata");
			return (Criteria) this;
		}

		public Criteria andExtensiondataLessThanOrEqualTo(String value) {
			addCriterion("u.ExtensionData <=", value, "extensiondata");
			return (Criteria) this;
		}

		public Criteria andExtensiondataLike(String value) {
			addCriterion("u.ExtensionData like", value, "extensiondata");
			return (Criteria) this;
		}

		public Criteria andExtensiondataNotLike(String value) {
			addCriterion("u.ExtensionData not like", value, "extensiondata");
			return (Criteria) this;
		}

		public Criteria andExtensiondataIn(List<String> values) {
			addCriterion("u.ExtensionData in", values, "extensiondata");
			return (Criteria) this;
		}

		public Criteria andExtensiondataNotIn(List<String> values) {
			addCriterion("u.ExtensionData not in", values, "extensiondata");
			return (Criteria) this;
		}

		public Criteria andExtensiondataBetween(String value1, String value2) {
			addCriterion("u.ExtensionData between", value1, value2, "extensiondata");
			return (Criteria) this;
		}

		public Criteria andExtensiondataNotBetween(String value1, String value2) {
			addCriterion("u.ExtensionData not between", value1, value2, "extensiondata");
			return (Criteria) this;
		}

		public Criteria andFirstnameIsNull() {
			addCriterion("u.FirstName is null");
			return (Criteria) this;
		}

		public Criteria andFirstnameIsNotNull() {
			addCriterion("u.FirstName is not null");
			return (Criteria) this;
		}

		public Criteria andFirstnameEqualTo(String value) {
			addCriterion("u.FirstName =", value, "firstname");
			return (Criteria) this;
		}

		public Criteria andFirstnameNotEqualTo(String value) {
			addCriterion("u.FirstName <>", value, "firstname");
			return (Criteria) this;
		}

		public Criteria andFirstnameGreaterThan(String value) {
			addCriterion("u.FirstName >", value, "firstname");
			return (Criteria) this;
		}

		public Criteria andFirstnameGreaterThanOrEqualTo(String value) {
			addCriterion("u.FirstName >=", value, "firstname");
			return (Criteria) this;
		}

		public Criteria andFirstnameLessThan(String value) {
			addCriterion("u.FirstName <", value, "firstname");
			return (Criteria) this;
		}

		public Criteria andFirstnameLessThanOrEqualTo(String value) {
			addCriterion("u.FirstName <=", value, "firstname");
			return (Criteria) this;
		}

		public Criteria andFirstnameLike(String value) {
			addCriterion("u.FirstName like", value, "firstname");
			return (Criteria) this;
		}

		public Criteria andFirstnameNotLike(String value) {
			addCriterion("u.FirstName not like", value, "firstname");
			return (Criteria) this;
		}

		public Criteria andFirstnameIn(List<String> values) {
			addCriterion("u.FirstName in", values, "firstname");
			return (Criteria) this;
		}

		public Criteria andFirstnameNotIn(List<String> values) {
			addCriterion("u.FirstName not in", values, "firstname");
			return (Criteria) this;
		}

		public Criteria andFirstnameBetween(String value1, String value2) {
			addCriterion("u.FirstName between", value1, value2, "firstname");
			return (Criteria) this;
		}

		public Criteria andFirstnameNotBetween(String value1, String value2) {
			addCriterion("u.FirstName not between", value1, value2, "firstname");
			return (Criteria) this;
		}

		public Criteria andIdnumberIsNull() {
			addCriterion("u.IdNumber is null");
			return (Criteria) this;
		}

		public Criteria andIdnumberIsNotNull() {
			addCriterion("u.IdNumber is not null");
			return (Criteria) this;
		}

		public Criteria andIdnumberEqualTo(String value) {
			addCriterion("u.IdNumber =", value, "idnumber");
			return (Criteria) this;
		}

		public Criteria andIdnumberNotEqualTo(String value) {
			addCriterion("u.IdNumber <>", value, "idnumber");
			return (Criteria) this;
		}

		public Criteria andIdnumberGreaterThan(String value) {
			addCriterion("u.IdNumber >", value, "idnumber");
			return (Criteria) this;
		}

		public Criteria andIdnumberGreaterThanOrEqualTo(String value) {
			addCriterion("u.IdNumber >=", value, "idnumber");
			return (Criteria) this;
		}

		public Criteria andIdnumberLessThan(String value) {
			addCriterion("u.IdNumber <", value, "idnumber");
			return (Criteria) this;
		}

		public Criteria andIdnumberLessThanOrEqualTo(String value) {
			addCriterion("u.IdNumber <=", value, "idnumber");
			return (Criteria) this;
		}

		public Criteria andIdnumberLike(String value) {
			addCriterion("u.IdNumber like", value, "idnumber");
			return (Criteria) this;
		}

		public Criteria andIdnumberNotLike(String value) {
			addCriterion("u.IdNumber not like", value, "idnumber");
			return (Criteria) this;
		}

		public Criteria andIdnumberIn(List<String> values) {
			addCriterion("u.IdNumber in", values, "idnumber");
			return (Criteria) this;
		}

		public Criteria andIdnumberNotIn(List<String> values) {
			addCriterion("u.IdNumber not in", values, "idnumber");
			return (Criteria) this;
		}

		public Criteria andIdnumberBetween(String value1, String value2) {
			addCriterion("u.IdNumber between", value1, value2, "idnumber");
			return (Criteria) this;
		}

		public Criteria andIdnumberNotBetween(String value1, String value2) {
			addCriterion("u.IdNumber not between", value1, value2, "idnumber");
			return (Criteria) this;
		}

		public Criteria andIsdeletedIsNull() {
			addCriterion("u.IsDeleted is null");
			return (Criteria) this;
		}

		public Criteria andIsdeletedIsNotNull() {
			addCriterion("u.IsDeleted is not null");
			return (Criteria) this;
		}

		public Criteria andIsdeletedEqualTo(Boolean value) {
			addCriterion("u.IsDeleted =", value, "isdeleted");
			return (Criteria) this;
		}

		public Criteria andIsdeletedNotEqualTo(Boolean value) {
			addCriterion("u.IsDeleted <>", value, "isdeleted");
			return (Criteria) this;
		}

		public Criteria andIsdeletedGreaterThan(Boolean value) {
			addCriterion("u.IsDeleted >", value, "isdeleted");
			return (Criteria) this;
		}

		public Criteria andIsdeletedGreaterThanOrEqualTo(Boolean value) {
			addCriterion("u.IsDeleted >=", value, "isdeleted");
			return (Criteria) this;
		}

		public Criteria andIsdeletedLessThan(Boolean value) {
			addCriterion("u.IsDeleted <", value, "isdeleted");
			return (Criteria) this;
		}

		public Criteria andIsdeletedLessThanOrEqualTo(Boolean value) {
			addCriterion("u.IsDeleted <=", value, "isdeleted");
			return (Criteria) this;
		}

		public Criteria andIsdeletedIn(List<Boolean> values) {
			addCriterion("u.IsDeleted in", values, "isdeleted");
			return (Criteria) this;
		}

		public Criteria andIsdeletedNotIn(List<Boolean> values) {
			addCriterion("u.IsDeleted not in", values, "isdeleted");
			return (Criteria) this;
		}

		public Criteria andIsdeletedBetween(Boolean value1, Boolean value2) {
			addCriterion("u.IsDeleted between", value1, value2, "isdeleted");
			return (Criteria) this;
		}

		public Criteria andIsdeletedNotBetween(Boolean value1, Boolean value2) {
			addCriterion("u.IsDeleted not between", value1, value2, "isdeleted");
			return (Criteria) this;
		}

		public Criteria andIsenabledIsNull() {
			addCriterion("u.IsEnabled is null");
			return (Criteria) this;
		}

		public Criteria andIsenabledIsNotNull() {
			addCriterion("u.IsEnabled is not null");
			return (Criteria) this;
		}

		public Criteria andIsenabledEqualTo(Boolean value) {
			addCriterion("u.IsEnabled =", value, "isenabled");
			return (Criteria) this;
		}

		public Criteria andIsenabledNotEqualTo(Boolean value) {
			addCriterion("u.IsEnabled <>", value, "isenabled");
			return (Criteria) this;
		}

		public Criteria andIsenabledGreaterThan(Boolean value) {
			addCriterion("u.IsEnabled >", value, "isenabled");
			return (Criteria) this;
		}

		public Criteria andIsenabledGreaterThanOrEqualTo(Boolean value) {
			addCriterion("u.IsEnabled >=", value, "isenabled");
			return (Criteria) this;
		}

		public Criteria andIsenabledLessThan(Boolean value) {
			addCriterion("u.IsEnabled <", value, "isenabled");
			return (Criteria) this;
		}

		public Criteria andIsenabledLessThanOrEqualTo(Boolean value) {
			addCriterion("u.IsEnabled <=", value, "isenabled");
			return (Criteria) this;
		}

		public Criteria andIsenabledIn(List<Boolean> values) {
			addCriterion("u.IsEnabled in", values, "isenabled");
			return (Criteria) this;
		}

		public Criteria andIsenabledNotIn(List<Boolean> values) {
			addCriterion("u.IsEnabled not in", values, "isenabled");
			return (Criteria) this;
		}

		public Criteria andIsenabledBetween(Boolean value1, Boolean value2) {
			addCriterion("u.IsEnabled between", value1, value2, "isenabled");
			return (Criteria) this;
		}

		public Criteria andIsenabledNotBetween(Boolean value1, Boolean value2) {
			addCriterion("u.IsEnabled not between", value1, value2, "isenabled");
			return (Criteria) this;
		}

		public Criteria andLastnameIsNull() {
			addCriterion("u.LastName is null");
			return (Criteria) this;
		}

		public Criteria andLastnameIsNotNull() {
			addCriterion("u.LastName is not null");
			return (Criteria) this;
		}

		public Criteria andLastnameEqualTo(String value) {
			addCriterion("u.LastName =", value, "lastname");
			return (Criteria) this;
		}

		public Criteria andLastnameNotEqualTo(String value) {
			addCriterion("u.LastName <>", value, "lastname");
			return (Criteria) this;
		}

		public Criteria andLastnameGreaterThan(String value) {
			addCriterion("u.LastName >", value, "lastname");
			return (Criteria) this;
		}

		public Criteria andLastnameGreaterThanOrEqualTo(String value) {
			addCriterion("u.LastName >=", value, "lastname");
			return (Criteria) this;
		}

		public Criteria andLastnameLessThan(String value) {
			addCriterion("u.LastName <", value, "lastname");
			return (Criteria) this;
		}

		public Criteria andLastnameLessThanOrEqualTo(String value) {
			addCriterion("u.LastName <=", value, "lastname");
			return (Criteria) this;
		}

		public Criteria andLastnameLike(String value) {
			addCriterion("u.LastName like", value, "lastname");
			return (Criteria) this;
		}

		public Criteria andLastnameNotLike(String value) {
			addCriterion("u.LastName not like", value, "lastname");
			return (Criteria) this;
		}

		public Criteria andLastnameIn(List<String> values) {
			addCriterion("u.LastName in", values, "lastname");
			return (Criteria) this;
		}

		public Criteria andLastnameNotIn(List<String> values) {
			addCriterion("u.LastName not in", values, "lastname");
			return (Criteria) this;
		}

		public Criteria andLastnameBetween(String value1, String value2) {
			addCriterion("u.LastName between", value1, value2, "lastname");
			return (Criteria) this;
		}

		public Criteria andLastnameNotBetween(String value1, String value2) {
			addCriterion("u.LastName not between", value1, value2, "lastname");
			return (Criteria) this;
		}

		public Criteria andMiddlenameIsNull() {
			addCriterion("u.MiddleName is null");
			return (Criteria) this;
		}

		public Criteria andMiddlenameIsNotNull() {
			addCriterion("u.MiddleName is not null");
			return (Criteria) this;
		}

		public Criteria andMiddlenameEqualTo(String value) {
			addCriterion("u.MiddleName =", value, "middlename");
			return (Criteria) this;
		}

		public Criteria andMiddlenameNotEqualTo(String value) {
			addCriterion("u.MiddleName <>", value, "middlename");
			return (Criteria) this;
		}

		public Criteria andMiddlenameGreaterThan(String value) {
			addCriterion("u.MiddleName >", value, "middlename");
			return (Criteria) this;
		}

		public Criteria andMiddlenameGreaterThanOrEqualTo(String value) {
			addCriterion("u.MiddleName >=", value, "middlename");
			return (Criteria) this;
		}

		public Criteria andMiddlenameLessThan(String value) {
			addCriterion("u.MiddleName <", value, "middlename");
			return (Criteria) this;
		}

		public Criteria andMiddlenameLessThanOrEqualTo(String value) {
			addCriterion("u.MiddleName <=", value, "middlename");
			return (Criteria) this;
		}

		public Criteria andMiddlenameLike(String value) {
			addCriterion("u.MiddleName like", value, "middlename");
			return (Criteria) this;
		}

		public Criteria andMiddlenameNotLike(String value) {
			addCriterion("u.MiddleName not like", value, "middlename");
			return (Criteria) this;
		}

		public Criteria andMiddlenameIn(List<String> values) {
			addCriterion("u.MiddleName in", values, "middlename");
			return (Criteria) this;
		}

		public Criteria andMiddlenameNotIn(List<String> values) {
			addCriterion("u.MiddleName not in", values, "middlename");
			return (Criteria) this;
		}

		public Criteria andMiddlenameBetween(String value1, String value2) {
			addCriterion("u.MiddleName between", value1, value2, "middlename");
			return (Criteria) this;
		}

		public Criteria andMiddlenameNotBetween(String value1, String value2) {
			addCriterion("u.MiddleName not between", value1, value2, "middlename");
			return (Criteria) this;
		}

		public Criteria andNameIsNull() {
			addCriterion("u.Name is null");
			return (Criteria) this;
		}

		public Criteria andNameIsNotNull() {
			addCriterion("u.Name is not null");
			return (Criteria) this;
		}

		public Criteria andNameEqualTo(String value) {
			addCriterion("u.Name =", value, "name");
			return (Criteria) this;
		}

		public Criteria andNameNotEqualTo(String value) {
			addCriterion("u.Name <>", value, "name");
			return (Criteria) this;
		}

		public Criteria andNameGreaterThan(String value) {
			addCriterion("u.Name >", value, "name");
			return (Criteria) this;
		}

		public Criteria andNameGreaterThanOrEqualTo(String value) {
			addCriterion("u.Name >=", value, "name");
			return (Criteria) this;
		}

		public Criteria andNameLessThan(String value) {
			addCriterion("u.Name <", value, "name");
			return (Criteria) this;
		}

		public Criteria andNameLessThanOrEqualTo(String value) {
			addCriterion("u.Name <=", value, "name");
			return (Criteria) this;
		}

		public Criteria andNameLike(String value) {
			addCriterion("u.Name like", value, "name");
			return (Criteria) this;
		}

		public Criteria andNameNotLike(String value) {
			addCriterion("u.Name not like", value, "name");
			return (Criteria) this;
		}

		public Criteria andNameIn(List<String> values) {
			addCriterion("u.Name in", values, "name");
			return (Criteria) this;
		}

		public Criteria andNameNotIn(List<String> values) {
			addCriterion("u.Name not in", values, "name");
			return (Criteria) this;
		}

		public Criteria andNameBetween(String value1, String value2) {
			addCriterion("u.Name between", value1, value2, "name");
			return (Criteria) this;
		}

		public Criteria andNameNotBetween(String value1, String value2) {
			addCriterion("u.Name not between", value1, value2, "name");
			return (Criteria) this;
		}

		public Criteria andSexIsNull() {
			addCriterion("u.Sex is null");
			return (Criteria) this;
		}

		public Criteria andSexIsNotNull() {
			addCriterion("u.Sex is not null");
			return (Criteria) this;
		}

		public Criteria andSexEqualTo(Integer value) {
			addCriterion("u.Sex =", value, "sex");
			return (Criteria) this;
		}

		public Criteria andSexNotEqualTo(Integer value) {
			addCriterion("u.Sex <>", value, "sex");
			return (Criteria) this;
		}

		public Criteria andSexGreaterThan(Integer value) {
			addCriterion("u.Sex >", value, "sex");
			return (Criteria) this;
		}

		public Criteria andSexGreaterThanOrEqualTo(Integer value) {
			addCriterion("u.Sex >=", value, "sex");
			return (Criteria) this;
		}

		public Criteria andSexLessThan(Integer value) {
			addCriterion("u.Sex <", value, "sex");
			return (Criteria) this;
		}

		public Criteria andSexLessThanOrEqualTo(Integer value) {
			addCriterion("u.Sex <=", value, "sex");
			return (Criteria) this;
		}

		public Criteria andSexIn(List<Integer> values) {
			addCriterion("u.Sex in", values, "sex");
			return (Criteria) this;
		}

		public Criteria andSexNotIn(List<Integer> values) {
			addCriterion("u.Sex not in", values, "sex");
			return (Criteria) this;
		}

		public Criteria andSexBetween(Integer value1, Integer value2) {
			addCriterion("u.Sex between", value1, value2, "sex");
			return (Criteria) this;
		}

		public Criteria andSexNotBetween(Integer value1, Integer value2) {
			addCriterion("u.Sex not between", value1, value2, "sex");
			return (Criteria) this;
		}

		public Criteria andSnIsNull() {
			addCriterion("u.Sn is null");
			return (Criteria) this;
		}

		public Criteria andSnIsNotNull() {
			addCriterion("u.Sn is not null");
			return (Criteria) this;
		}

		public Criteria andSnEqualTo(Integer value) {
			addCriterion("u.Sn =", value, "sn");
			return (Criteria) this;
		}

		public Criteria andSnNotEqualTo(Integer value) {
			addCriterion("u.Sn <>", value, "sn");
			return (Criteria) this;
		}

		public Criteria andSnGreaterThan(Integer value) {
			addCriterion("u.Sn >", value, "sn");
			return (Criteria) this;
		}

		public Criteria andSnGreaterThanOrEqualTo(Integer value) {
			addCriterion("u.Sn >=", value, "sn");
			return (Criteria) this;
		}

		public Criteria andSnLessThan(Integer value) {
			addCriterion("u.Sn <", value, "sn");
			return (Criteria) this;
		}

		public Criteria andSnLessThanOrEqualTo(Integer value) {
			addCriterion("u.Sn <=", value, "sn");
			return (Criteria) this;
		}

		public Criteria andSnIn(List<Integer> values) {
			addCriterion("u.Sn in", values, "sn");
			return (Criteria) this;
		}

		public Criteria andSnNotIn(List<Integer> values) {
			addCriterion("u.Sn not in", values, "sn");
			return (Criteria) this;
		}

		public Criteria andSnBetween(Integer value1, Integer value2) {
			addCriterion("u.Sn between", value1, value2, "sn");
			return (Criteria) this;
		}

		public Criteria andSnNotBetween(Integer value1, Integer value2) {
			addCriterion("u.Sn not between", value1, value2, "sn");
			return (Criteria) this;
		}

		public Criteria andTypeIsNull() {
			addCriterion("u.Type is null");
			return (Criteria) this;
		}

		public Criteria andTypeIsNotNull() {
			addCriterion("u.Type is not null");
			return (Criteria) this;
		}

		public Criteria andTypeEqualTo(String value) {
			addCriterion("u.Type =", value, "type");
			return (Criteria) this;
		}

		public Criteria andTypeNotEqualTo(String value) {
			addCriterion("u.Type <>", value, "type");
			return (Criteria) this;
		}

		public Criteria andTypeGreaterThan(String value) {
			addCriterion("u.Type >", value, "type");
			return (Criteria) this;
		}

		public Criteria andTypeGreaterThanOrEqualTo(String value) {
			addCriterion("u.Type >=", value, "type");
			return (Criteria) this;
		}

		public Criteria andTypeLessThan(String value) {
			addCriterion("u.Type <", value, "type");
			return (Criteria) this;
		}

		public Criteria andTypeLessThanOrEqualTo(String value) {
			addCriterion("u.Type <=", value, "type");
			return (Criteria) this;
		}

		public Criteria andTypeLike(String value) {
			addCriterion("u.Type like", value, "type");
			return (Criteria) this;
		}

		public Criteria andTypeNotLike(String value) {
			addCriterion("u.Type not like", value, "type");
			return (Criteria) this;
		}

		public Criteria andTypeIn(List<String> values) {
			addCriterion("u.Type in", values, "type");
			return (Criteria) this;
		}

		public Criteria andTypeNotIn(List<String> values) {
			addCriterion("u.Type not in", values, "type");
			return (Criteria) this;
		}

		public Criteria andTypeBetween(String value1, String value2) {
			addCriterion("u.Type between", value1, value2, "type");
			return (Criteria) this;
		}

		public Criteria andTypeNotBetween(String value1, String value2) {
			addCriterion("u.Type not between", value1, value2, "type");
			return (Criteria) this;
		}

		public Criteria andWorknumberIsNull() {
			addCriterion("u.WorkNumber is null");
			return (Criteria) this;
		}

		public Criteria andWorknumberIsNotNull() {
			addCriterion("u.WorkNumber is not null");
			return (Criteria) this;
		}

		public Criteria andWorknumberEqualTo(String value) {
			addCriterion("u.WorkNumber =", value, "worknumber");
			return (Criteria) this;
		}

		public Criteria andWorknumberNotEqualTo(String value) {
			addCriterion("u.WorkNumber <>", value, "worknumber");
			return (Criteria) this;
		}

		public Criteria andWorknumberGreaterThan(String value) {
			addCriterion("u.WorkNumber >", value, "worknumber");
			return (Criteria) this;
		}

		public Criteria andWorknumberGreaterThanOrEqualTo(String value) {
			addCriterion("u.WorkNumber >=", value, "worknumber");
			return (Criteria) this;
		}

		public Criteria andWorknumberLessThan(String value) {
			addCriterion("u.WorkNumber <", value, "worknumber");
			return (Criteria) this;
		}

		public Criteria andWorknumberLessThanOrEqualTo(String value) {
			addCriterion("u.WorkNumber <=", value, "worknumber");
			return (Criteria) this;
		}

		public Criteria andWorknumberLike(String value) {
			addCriterion("u.WorkNumber like", value, "worknumber");
			return (Criteria) this;
		}

		public Criteria andWorknumberNotLike(String value) {
			addCriterion("u.WorkNumber not like", value, "worknumber");
			return (Criteria) this;
		}

		public Criteria andWorknumberIn(List<String> values) {
			addCriterion("u.WorkNumber in", values, "worknumber");
			return (Criteria) this;
		}

		public Criteria andWorknumberNotIn(List<String> values) {
			addCriterion("u.WorkNumber not in", values, "worknumber");
			return (Criteria) this;
		}

		public Criteria andWorknumberBetween(String value1, String value2) {
			addCriterion("u.WorkNumber between", value1, value2, "worknumber");
			return (Criteria) this;
		}

		public Criteria andWorknumberNotBetween(String value1, String value2) {
			addCriterion("u.WorkNumber not between", value1, value2, "worknumber");
			return (Criteria) this;
		}
	}

	/**
	 * This class was generated by MyBatis Generator. This class corresponds to the database table RS_User
	 * @mbggenerated  Wed Jul 26 18:19:56 CST 2017
	 */
	public static class Criterion {
		private String condition;
		private Object value;
		private Object secondValue;
		private boolean noValue;
		private boolean singleValue;
		private boolean betweenValue;
		private boolean listValue;
		private String typeHandler;

		public String getCondition() {
			return condition;
		}

		public Object getValue() {
			return value;
		}

		public Object getSecondValue() {
			return secondValue;
		}

		public boolean isNoValue() {
			return noValue;
		}

		public boolean isSingleValue() {
			return singleValue;
		}

		public boolean isBetweenValue() {
			return betweenValue;
		}

		public boolean isListValue() {
			return listValue;
		}

		public String getTypeHandler() {
			return typeHandler;
		}

		protected Criterion(String condition) {
			super();
			this.condition = condition;
			this.typeHandler = null;
			this.noValue = true;
		}

		protected Criterion(String condition, Object value, String typeHandler) {
			super();
			this.condition = condition;
			this.value = value;
			this.typeHandler = typeHandler;
			if (value instanceof List<?>) {
				this.listValue = true;
			} else {
				this.singleValue = true;
			}
		}

		protected Criterion(String condition, Object value) {
			this(condition, value, null);
		}

		protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
			super();
			this.condition = condition;
			this.value = value;
			this.secondValue = secondValue;
			this.typeHandler = typeHandler;
			this.betweenValue = true;
		}

		protected Criterion(String condition, Object value, Object secondValue) {
			this(condition, value, secondValue, null);
		}
	}

	/**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table RS_User
     *
     * @mbggenerated do_not_delete_during_merge Wed Jul 26 11:51:31 CST 2017
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }
}