package com.dynastech.system.mapper;

import java.util.List;

import org.apache.ibatis.annotations.Param;

import com.dynastech.system.entity.User;
import com.dynastech.system.entity.UserExample;

public interface UserMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table RS_User
     *
     * @mbggenerated Wed Jul 26 18:19:56 CST 2017
     */
    int countByExample(UserExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table RS_User
     *
     * @mbggenerated Wed Jul 26 18:19:56 CST 2017
     */
    int deleteByExample(UserExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table RS_User
     *
     * @mbggenerated Wed Jul 26 18:19:56 CST 2017
     */
    int deleteByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table RS_User
     *
     * @mbggenerated Wed Jul 26 18:19:56 CST 2017
     */
    int insert(User record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table RS_User
     *
     * @mbggenerated Wed Jul 26 18:19:56 CST 2017
     */
    int insertSelective(User record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table RS_User
     *
     * @mbggenerated Wed Jul 26 18:19:56 CST 2017
     */
    List<User> selectByExample(UserExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table RS_User
     *
     * @mbggenerated Wed Jul 26 18:19:56 CST 2017
     */
    User selectByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table RS_User
     *
     * @mbggenerated Wed Jul 26 18:19:56 CST 2017
     */
    int updateByExampleSelective(@Param("record") User record, @Param("example") UserExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table RS_User
     *
     * @mbggenerated Wed Jul 26 18:19:56 CST 2017
     */
    int updateByExample(@Param("record") User record, @Param("example") UserExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table RS_User
     *
     * @mbggenerated Wed Jul 26 18:19:56 CST 2017
     */
    int updateByPrimaryKeySelective(User record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table RS_User
     *
     * @mbggenerated Wed Jul 26 18:19:56 CST 2017
     */
    int updateByPrimaryKey(User record);
    
    /**
     * 根据orgId 查询user
     * @param orgId
     * @return
     */
    List<User>selectUsersByOrgId(@Param("orgId")String orgId,@Param("str")String str);
    
    /**
     * 查询该部门的领导  （暂未过滤）
     * @param orgIds
     * @return
     */
    List<User>findLeadersByOrgId(@Param("orgIds")List<String> orgIds);
    
    /**
     * 通过角色名称 查询对应的用户 （目前只是 用于查询 评分人用）
     * @param roleName
     * @return
     */
    List<User>findUsersByRoleName(@Param("roleName")String roleName);
}