package com.dynastech.model.entity;

public class CheckDetail {

	private String id;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column T_Apply_CheckDetail.applyId
	 * @mbggenerated  Tue Sep 26 14:13:16 CST 2017
	 */
	private String applyid;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column T_Apply_CheckDetail.nodeName
	 * @mbggenerated  Tue Sep 26 14:13:16 CST 2017
	 */
	private String nodename;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column T_Apply_CheckDetail.result
	 * @mbggenerated  Tue Sep 26 14:13:16 CST 2017
	 */
	private Boolean result;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column T_Apply_CheckDetail.opinion
	 * @mbggenerated  Tue Sep 26 14:13:16 CST 2017
	 */
	private String opinion;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column T_Apply_CheckDetail.createdTime
	 * @mbggenerated  Tue Sep 26 14:13:16 CST 2017
	 */
	private String createdtime;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column T_Apply_CheckDetail.userId
	 * @mbggenerated  Tue Sep 26 14:13:16 CST 2017
	 */
	private String userid;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column T_Apply_CheckDetail.userName
	 * @mbggenerated  Tue Sep 26 14:13:16 CST 2017
	 */
	private String username;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column T_Apply_CheckDetail.taskId
	 * @mbggenerated  Tue Sep 26 14:13:16 CST 2017
	 */
	private String taskid;

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column T_Apply_CheckDetail.id
	 * @return  the value of T_Apply_CheckDetail.id
	 * @mbggenerated  Tue Sep 26 14:13:16 CST 2017
	 */
	public String getId() {
		return id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column T_Apply_CheckDetail.id
	 * @param id  the value for T_Apply_CheckDetail.id
	 * @mbggenerated  Tue Sep 26 14:13:16 CST 2017
	 */
	public void setId(String id) {
		this.id = id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column T_Apply_CheckDetail.applyId
	 * @return  the value of T_Apply_CheckDetail.applyId
	 * @mbggenerated  Tue Sep 26 14:13:16 CST 2017
	 */
	public String getApplyid() {
		return applyid;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column T_Apply_CheckDetail.applyId
	 * @param applyid  the value for T_Apply_CheckDetail.applyId
	 * @mbggenerated  Tue Sep 26 14:13:16 CST 2017
	 */
	public void setApplyid(String applyid) {
		this.applyid = applyid;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column T_Apply_CheckDetail.nodeName
	 * @return  the value of T_Apply_CheckDetail.nodeName
	 * @mbggenerated  Tue Sep 26 14:13:16 CST 2017
	 */
	public String getNodename() {
		return nodename;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column T_Apply_CheckDetail.nodeName
	 * @param nodename  the value for T_Apply_CheckDetail.nodeName
	 * @mbggenerated  Tue Sep 26 14:13:16 CST 2017
	 */
	public void setNodename(String nodename) {
		this.nodename = nodename;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column T_Apply_CheckDetail.result
	 * @return  the value of T_Apply_CheckDetail.result
	 * @mbggenerated  Tue Sep 26 14:13:16 CST 2017
	 */
	public Boolean getResult() {
		return result;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column T_Apply_CheckDetail.result
	 * @param result  the value for T_Apply_CheckDetail.result
	 * @mbggenerated  Tue Sep 26 14:13:16 CST 2017
	 */
	public void setResult(Boolean result) {
		this.result = result;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column T_Apply_CheckDetail.opinion
	 * @return  the value of T_Apply_CheckDetail.opinion
	 * @mbggenerated  Tue Sep 26 14:13:16 CST 2017
	 */
	public String getOpinion() {
		return opinion;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column T_Apply_CheckDetail.opinion
	 * @param opinion  the value for T_Apply_CheckDetail.opinion
	 * @mbggenerated  Tue Sep 26 14:13:16 CST 2017
	 */
	public void setOpinion(String opinion) {
		this.opinion = opinion;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column T_Apply_CheckDetail.createdTime
	 * @return  the value of T_Apply_CheckDetail.createdTime
	 * @mbggenerated  Tue Sep 26 14:13:16 CST 2017
	 */
	public String getCreatedtime() {
		return createdtime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column T_Apply_CheckDetail.createdTime
	 * @param createdtime  the value for T_Apply_CheckDetail.createdTime
	 * @mbggenerated  Tue Sep 26 14:13:16 CST 2017
	 */
	public void setCreatedtime(String createdtime) {
		this.createdtime = createdtime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column T_Apply_CheckDetail.userId
	 * @return  the value of T_Apply_CheckDetail.userId
	 * @mbggenerated  Tue Sep 26 14:13:16 CST 2017
	 */
	public String getUserid() {
		return userid;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column T_Apply_CheckDetail.userId
	 * @param userid  the value for T_Apply_CheckDetail.userId
	 * @mbggenerated  Tue Sep 26 14:13:16 CST 2017
	 */
	public void setUserid(String userid) {
		this.userid = userid;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column T_Apply_CheckDetail.userName
	 * @return  the value of T_Apply_CheckDetail.userName
	 * @mbggenerated  Tue Sep 26 14:13:16 CST 2017
	 */
	public String getUsername() {
		return username;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column T_Apply_CheckDetail.userName
	 * @param username  the value for T_Apply_CheckDetail.userName
	 * @mbggenerated  Tue Sep 26 14:13:16 CST 2017
	 */
	public void setUsername(String username) {
		this.username = username;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column T_Apply_CheckDetail.taskId
	 * @return  the value of T_Apply_CheckDetail.taskId
	 * @mbggenerated  Tue Sep 26 14:13:16 CST 2017
	 */
	public String getTaskid() {
		return taskid;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column T_Apply_CheckDetail.taskId
	 * @param taskid  the value for T_Apply_CheckDetail.taskId
	 * @mbggenerated  Tue Sep 26 14:13:16 CST 2017
	 */
	public void setTaskid(String taskid) {
		this.taskid = taskid;
	}
}