package com.dynastech.model.entity;

import java.util.ArrayList;
import java.util.Date;
import java.util.List;

public class ExamExample {
    /**
	 * This field was generated by MyBatis Generator. This field corresponds to the database table t_exam
	 * @mbggenerated  Thu Sep 28 10:23:09 CST 2017
	 */
	protected String orderByClause;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database table t_exam
	 * @mbggenerated  Thu Sep 28 10:23:09 CST 2017
	 */
	protected boolean distinct;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database table t_exam
	 * @mbggenerated  Thu Sep 28 10:23:09 CST 2017
	 */
	protected List<Criteria> oredCriteria;

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table t_exam
	 * @mbggenerated  Thu Sep 28 10:23:09 CST 2017
	 */
	public ExamExample() {
		oredCriteria = new ArrayList<Criteria>();
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table t_exam
	 * @mbggenerated  Thu Sep 28 10:23:09 CST 2017
	 */
	public void setOrderByClause(String orderByClause) {
		this.orderByClause = orderByClause;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table t_exam
	 * @mbggenerated  Thu Sep 28 10:23:09 CST 2017
	 */
	public String getOrderByClause() {
		return orderByClause;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table t_exam
	 * @mbggenerated  Thu Sep 28 10:23:09 CST 2017
	 */
	public void setDistinct(boolean distinct) {
		this.distinct = distinct;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table t_exam
	 * @mbggenerated  Thu Sep 28 10:23:09 CST 2017
	 */
	public boolean isDistinct() {
		return distinct;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table t_exam
	 * @mbggenerated  Thu Sep 28 10:23:09 CST 2017
	 */
	public List<Criteria> getOredCriteria() {
		return oredCriteria;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table t_exam
	 * @mbggenerated  Thu Sep 28 10:23:09 CST 2017
	 */
	public void or(Criteria criteria) {
		oredCriteria.add(criteria);
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table t_exam
	 * @mbggenerated  Thu Sep 28 10:23:09 CST 2017
	 */
	public Criteria or() {
		Criteria criteria = createCriteriaInternal();
		oredCriteria.add(criteria);
		return criteria;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table t_exam
	 * @mbggenerated  Thu Sep 28 10:23:09 CST 2017
	 */
	public Criteria createCriteria() {
		Criteria criteria = createCriteriaInternal();
		if (oredCriteria.size() == 0) {
			oredCriteria.add(criteria);
		}
		return criteria;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table t_exam
	 * @mbggenerated  Thu Sep 28 10:23:09 CST 2017
	 */
	protected Criteria createCriteriaInternal() {
		Criteria criteria = new Criteria();
		return criteria;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table t_exam
	 * @mbggenerated  Thu Sep 28 10:23:09 CST 2017
	 */
	public void clear() {
		oredCriteria.clear();
		orderByClause = null;
		distinct = false;
	}

	/**
	 * This class was generated by MyBatis Generator. This class corresponds to the database table t_exam
	 * @mbggenerated  Thu Sep 28 10:23:09 CST 2017
	 */
	protected abstract static class GeneratedCriteria {
		protected List<Criterion> criteria;

		protected GeneratedCriteria() {
			super();
			criteria = new ArrayList<Criterion>();
		}

		public boolean isValid() {
			return criteria.size() > 0;
		}

		public List<Criterion> getAllCriteria() {
			return criteria;
		}

		public List<Criterion> getCriteria() {
			return criteria;
		}

		protected void addCriterion(String condition) {
			if (condition == null) {
				throw new RuntimeException("Value for condition cannot be null");
			}
			criteria.add(new Criterion(condition));
		}

		protected void addCriterion(String condition, Object value, String property) {
			if (value == null) {
				throw new RuntimeException("Value for " + property + " cannot be null");
			}
			criteria.add(new Criterion(condition, value));
		}

		protected void addCriterion(String condition, Object value1, Object value2, String property) {
			if (value1 == null || value2 == null) {
				throw new RuntimeException("Between values for " + property + " cannot be null");
			}
			criteria.add(new Criterion(condition, value1, value2));
		}

		public Criteria andIdIsNull() {
			addCriterion("te.id is null");
			return (Criteria) this;
		}

		public Criteria andIdIsNotNull() {
			addCriterion("te.id is not null");
			return (Criteria) this;
		}

		public Criteria andIdEqualTo(String value) {
			addCriterion("te.id =", value, "id");
			return (Criteria) this;
		}

		public Criteria andIdNotEqualTo(String value) {
			addCriterion("te.id <>", value, "id");
			return (Criteria) this;
		}

		public Criteria andIdGreaterThan(String value) {
			addCriterion("te.id >", value, "id");
			return (Criteria) this;
		}

		public Criteria andIdGreaterThanOrEqualTo(String value) {
			addCriterion("te.id >=", value, "id");
			return (Criteria) this;
		}

		public Criteria andIdLessThan(String value) {
			addCriterion("te.id <", value, "id");
			return (Criteria) this;
		}

		public Criteria andIdLessThanOrEqualTo(String value) {
			addCriterion("te.id <=", value, "id");
			return (Criteria) this;
		}

		public Criteria andIdIn(List<String> values) {
			addCriterion("te.id in", values, "id");
			return (Criteria) this;
		}

		public Criteria andIdNotIn(List<String> values) {
			addCriterion("te.id not in", values, "id");
			return (Criteria) this;
		}

		public Criteria andIdBetween(String value1, String value2) {
			addCriterion("te.id between", value1, value2, "id");
			return (Criteria) this;
		}

		public Criteria andIdNotBetween(String value1, String value2) {
			addCriterion("te.id not between", value1, value2, "id");
			return (Criteria) this;
		}

		public Criteria andNameIsNull() {
			addCriterion("te.name is null");
			return (Criteria) this;
		}

		public Criteria andNameIsNotNull() {
			addCriterion("te.name is not null");
			return (Criteria) this;
		}

		public Criteria andNameEqualTo(String value) {
			addCriterion("te.name =", value, "name");
			return (Criteria) this;
		}

		public Criteria andNameNotEqualTo(String value) {
			addCriterion("te.name <>", value, "name");
			return (Criteria) this;
		}

		public Criteria andNameGreaterThan(String value) {
			addCriterion("te.name >", value, "name");
			return (Criteria) this;
		}

		public Criteria andNameGreaterThanOrEqualTo(String value) {
			addCriterion("te.name >=", value, "name");
			return (Criteria) this;
		}

		public Criteria andNameLessThan(String value) {
			addCriterion("te.name <", value, "name");
			return (Criteria) this;
		}

		public Criteria andNameLessThanOrEqualTo(String value) {
			addCriterion("te.name <=", value, "name");
			return (Criteria) this;
		}

		public Criteria andNameIn(List<String> values) {
			addCriterion("te.name in", values, "name");
			return (Criteria) this;
		}

		public Criteria andNameNotIn(List<String> values) {
			addCriterion("te.name not in", values, "name");
			return (Criteria) this;
		}

		public Criteria andNameBetween(String value1, String value2) {
			addCriterion("te.name between", value1, value2, "name");
			return (Criteria) this;
		}

		public Criteria andNameNotBetween(String value1, String value2) {
			addCriterion("te.name not between", value1, value2, "name");
			return (Criteria) this;
		}

		public Criteria andKindIsNull() {
			addCriterion("te.kind is null");
			return (Criteria) this;
		}

		public Criteria andKindIsNotNull() {
			addCriterion("te.kind is not null");
			return (Criteria) this;
		}

		public Criteria andKindEqualTo(String value) {
			addCriterion("te.kind =", value, "kind");
			return (Criteria) this;
		}

		public Criteria andKindNotEqualTo(String value) {
			addCriterion("te.kind <>", value, "kind");
			return (Criteria) this;
		}

		public Criteria andKindGreaterThan(String value) {
			addCriterion("te.kind >", value, "kind");
			return (Criteria) this;
		}

		public Criteria andKindGreaterThanOrEqualTo(String value) {
			addCriterion("te.kind >=", value, "kind");
			return (Criteria) this;
		}

		public Criteria andKindLessThan(String value) {
			addCriterion("te.kind <", value, "kind");
			return (Criteria) this;
		}

		public Criteria andKindLessThanOrEqualTo(String value) {
			addCriterion("te.kind <=", value, "kind");
			return (Criteria) this;
		}

		public Criteria andKindIn(List<String> values) {
			addCriterion("te.kind in", values, "kind");
			return (Criteria) this;
		}

		public Criteria andKindNotIn(List<String> values) {
			addCriterion("te.kind not in", values, "kind");
			return (Criteria) this;
		}

		public Criteria andKindBetween(String value1, String value2) {
			addCriterion("te.kind between", value1, value2, "kind");
			return (Criteria) this;
		}

		public Criteria andKindNotBetween(String value1, String value2) {
			addCriterion("te.kind not between", value1, value2, "kind");
			return (Criteria) this;
		}

		public Criteria andDateIsNull() {
			addCriterion("te.date is null");
			return (Criteria) this;
		}

		public Criteria andDateIsNotNull() {
			addCriterion("te.date is not null");
			return (Criteria) this;
		}

		public Criteria andDateEqualTo(String value) {
			addCriterion("te.date =", value, "date");
			return (Criteria) this;
		}

		public Criteria andDateNotEqualTo(String value) {
			addCriterion("te.date <>", value, "date");
			return (Criteria) this;
		}

		public Criteria andDateGreaterThan(String value) {
			addCriterion("te.date >", value, "date");
			return (Criteria) this;
		}

		public Criteria andDateGreaterThanOrEqualTo(String value) {
			addCriterion("te.date >=", value, "date");
			return (Criteria) this;
		}

		public Criteria andDateLessThan(String value) {
			addCriterion("te.date <", value, "date");
			return (Criteria) this;
		}

		public Criteria andDateLessThanOrEqualTo(String value) {
			addCriterion("te.date <=", value, "date");
			return (Criteria) this;
		}

		public Criteria andDateIn(List<String> values) {
			addCriterion("te.date in", values, "date");
			return (Criteria) this;
		}

		public Criteria andDateNotIn(List<String> values) {
			addCriterion("te.date not in", values, "date");
			return (Criteria) this;
		}

		public Criteria andDateBetween(String value1, String value2) {
			addCriterion("te.date between", value1, value2, "date");
			return (Criteria) this;
		}

		public Criteria andDateNotBetween(String value1, String value2) {
			addCriterion("te.date not between", value1, value2, "date");
			return (Criteria) this;
		}

		public Criteria andScoreIsNull() {
			addCriterion("te.score is null");
			return (Criteria) this;
		}

		public Criteria andScoreIsNotNull() {
			addCriterion("te.score is not null");
			return (Criteria) this;
		}

		public Criteria andScoreEqualTo(String value) {
			addCriterion("te.score =", value, "score");
			return (Criteria) this;
		}

		public Criteria andScoreNotEqualTo(String value) {
			addCriterion("te.score <>", value, "score");
			return (Criteria) this;
		}

		public Criteria andScoreGreaterThan(String value) {
			addCriterion("te.score >", value, "score");
			return (Criteria) this;
		}

		public Criteria andScoreGreaterThanOrEqualTo(String value) {
			addCriterion("te.score >=", value, "score");
			return (Criteria) this;
		}

		public Criteria andScoreLessThan(String value) {
			addCriterion("te.score <", value, "score");
			return (Criteria) this;
		}

		public Criteria andScoreLessThanOrEqualTo(String value) {
			addCriterion("te.score <=", value, "score");
			return (Criteria) this;
		}

		public Criteria andScoreIn(List<String> values) {
			addCriterion("te.score in", values, "score");
			return (Criteria) this;
		}

		public Criteria andScoreNotIn(List<String> values) {
			addCriterion("te.score not in", values, "score");
			return (Criteria) this;
		}

		public Criteria andScoreBetween(String value1, String value2) {
			addCriterion("te.score between", value1, value2, "score");
			return (Criteria) this;
		}

		public Criteria andScoreNotBetween(String value1, String value2) {
			addCriterion("te.score not between", value1, value2, "score");
			return (Criteria) this;
		}

		public Criteria andDatetimecreatedIsNull() {
			addCriterion("te.DateTimeCreated is null");
			return (Criteria) this;
		}

		public Criteria andDatetimecreatedIsNotNull() {
			addCriterion("te.DateTimeCreated is not null");
			return (Criteria) this;
		}

		public Criteria andDatetimecreatedEqualTo(Date value) {
			addCriterion("te.DateTimeCreated =", value, "datetimecreated");
			return (Criteria) this;
		}

		public Criteria andDatetimecreatedNotEqualTo(Date value) {
			addCriterion("te.DateTimeCreated <>", value, "datetimecreated");
			return (Criteria) this;
		}

		public Criteria andDatetimecreatedGreaterThan(Date value) {
			addCriterion("te.DateTimeCreated >", value, "datetimecreated");
			return (Criteria) this;
		}

		public Criteria andDatetimecreatedGreaterThanOrEqualTo(Date value) {
			addCriterion("te.DateTimeCreated >=", value, "datetimecreated");
			return (Criteria) this;
		}

		public Criteria andDatetimecreatedLessThan(Date value) {
			addCriterion("te.DateTimeCreated <", value, "datetimecreated");
			return (Criteria) this;
		}

		public Criteria andDatetimecreatedLessThanOrEqualTo(Date value) {
			addCriterion("te.DateTimeCreated <=", value, "datetimecreated");
			return (Criteria) this;
		}

		public Criteria andDatetimecreatedIn(List<Date> values) {
			addCriterion("te.DateTimeCreated in", values, "datetimecreated");
			return (Criteria) this;
		}

		public Criteria andDatetimecreatedNotIn(List<Date> values) {
			addCriterion("te.DateTimeCreated not in", values, "datetimecreated");
			return (Criteria) this;
		}

		public Criteria andDatetimecreatedBetween(Date value1, Date value2) {
			addCriterion("te.DateTimeCreated between", value1, value2, "datetimecreated");
			return (Criteria) this;
		}

		public Criteria andDatetimecreatedNotBetween(Date value1, Date value2) {
			addCriterion("te.DateTimeCreated not between", value1, value2, "datetimecreated");
			return (Criteria) this;
		}

		public Criteria andDatetimemodifiedIsNull() {
			addCriterion("te.DateTimeModified is null");
			return (Criteria) this;
		}

		public Criteria andDatetimemodifiedIsNotNull() {
			addCriterion("te.DateTimeModified is not null");
			return (Criteria) this;
		}

		public Criteria andDatetimemodifiedEqualTo(Date value) {
			addCriterion("te.DateTimeModified =", value, "datetimemodified");
			return (Criteria) this;
		}

		public Criteria andDatetimemodifiedNotEqualTo(Date value) {
			addCriterion("te.DateTimeModified <>", value, "datetimemodified");
			return (Criteria) this;
		}

		public Criteria andDatetimemodifiedGreaterThan(Date value) {
			addCriterion("te.DateTimeModified >", value, "datetimemodified");
			return (Criteria) this;
		}

		public Criteria andDatetimemodifiedGreaterThanOrEqualTo(Date value) {
			addCriterion("te.DateTimeModified >=", value, "datetimemodified");
			return (Criteria) this;
		}

		public Criteria andDatetimemodifiedLessThan(Date value) {
			addCriterion("te.DateTimeModified <", value, "datetimemodified");
			return (Criteria) this;
		}

		public Criteria andDatetimemodifiedLessThanOrEqualTo(Date value) {
			addCriterion("te.DateTimeModified <=", value, "datetimemodified");
			return (Criteria) this;
		}

		public Criteria andDatetimemodifiedIn(List<Date> values) {
			addCriterion("te.DateTimeModified in", values, "datetimemodified");
			return (Criteria) this;
		}

		public Criteria andDatetimemodifiedNotIn(List<Date> values) {
			addCriterion("te.DateTimeModified not in", values, "datetimemodified");
			return (Criteria) this;
		}

		public Criteria andDatetimemodifiedBetween(Date value1, Date value2) {
			addCriterion("te.DateTimeModified between", value1, value2, "datetimemodified");
			return (Criteria) this;
		}

		public Criteria andDatetimemodifiedNotBetween(Date value1, Date value2) {
			addCriterion("te.DateTimeModified not between", value1, value2, "datetimemodified");
			return (Criteria) this;
		}

		public Criteria andIsdeletedIsNull() {
			addCriterion("te.isDeleted is null");
			return (Criteria) this;
		}

		public Criteria andIsdeletedIsNotNull() {
			addCriterion("te.isDeleted is not null");
			return (Criteria) this;
		}

		public Criteria andIsdeletedEqualTo(Boolean value) {
			addCriterion("te.isDeleted =", value, "isdeleted");
			return (Criteria) this;
		}

		public Criteria andIsdeletedNotEqualTo(Boolean value) {
			addCriterion("te.isDeleted <>", value, "isdeleted");
			return (Criteria) this;
		}

		public Criteria andIsdeletedGreaterThan(Boolean value) {
			addCriterion("te.isDeleted >", value, "isdeleted");
			return (Criteria) this;
		}

		public Criteria andIsdeletedGreaterThanOrEqualTo(Boolean value) {
			addCriterion("te.isDeleted >=", value, "isdeleted");
			return (Criteria) this;
		}

		public Criteria andIsdeletedLessThan(Boolean value) {
			addCriterion("te.isDeleted <", value, "isdeleted");
			return (Criteria) this;
		}

		public Criteria andIsdeletedLessThanOrEqualTo(Boolean value) {
			addCriterion("te.isDeleted <=", value, "isdeleted");
			return (Criteria) this;
		}

		public Criteria andIsdeletedIn(List<Boolean> values) {
			addCriterion("te.isDeleted in", values, "isdeleted");
			return (Criteria) this;
		}

		public Criteria andIsdeletedNotIn(List<Boolean> values) {
			addCriterion("te.isDeleted not in", values, "isdeleted");
			return (Criteria) this;
		}

		public Criteria andIsdeletedBetween(Boolean value1, Boolean value2) {
			addCriterion("te.isDeleted between", value1, value2, "isdeleted");
			return (Criteria) this;
		}

		public Criteria andIsdeletedNotBetween(Boolean value1, Boolean value2) {
			addCriterion("te.isDeleted not between", value1, value2, "isdeleted");
			return (Criteria) this;
		}

		public Criteria andSeqIsNull() {
			addCriterion("te.seq is null");
			return (Criteria) this;
		}

		public Criteria andSeqIsNotNull() {
			addCriterion("te.seq is not null");
			return (Criteria) this;
		}

		public Criteria andSeqEqualTo(String value) {
			addCriterion("te.seq =", value, "seq");
			return (Criteria) this;
		}

		public Criteria andSeqNotEqualTo(String value) {
			addCriterion("te.seq <>", value, "seq");
			return (Criteria) this;
		}

		public Criteria andSeqGreaterThan(String value) {
			addCriterion("te.seq >", value, "seq");
			return (Criteria) this;
		}

		public Criteria andSeqGreaterThanOrEqualTo(String value) {
			addCriterion("te.seq >=", value, "seq");
			return (Criteria) this;
		}

		public Criteria andSeqLessThan(String value) {
			addCriterion("te.seq <", value, "seq");
			return (Criteria) this;
		}

		public Criteria andSeqLessThanOrEqualTo(String value) {
			addCriterion("te.seq <=", value, "seq");
			return (Criteria) this;
		}

		public Criteria andSeqIn(List<String> values) {
			addCriterion("te.seq in", values, "seq");
			return (Criteria) this;
		}

		public Criteria andSeqNotIn(List<String> values) {
			addCriterion("te.seq not in", values, "seq");
			return (Criteria) this;
		}

		public Criteria andSeqBetween(String value1, String value2) {
			addCriterion("te.seq between", value1, value2, "seq");
			return (Criteria) this;
		}

		public Criteria andSeqNotBetween(String value1, String value2) {
			addCriterion("te.seq not between", value1, value2, "seq");
			return (Criteria) this;
		}

		public Criteria andLevelIsNull() {
			addCriterion("te.level is null");
			return (Criteria) this;
		}

		public Criteria andLevelIsNotNull() {
			addCriterion("te.level is not null");
			return (Criteria) this;
		}

		public Criteria andLevelEqualTo(String value) {
			addCriterion("te.level =", value, "level");
			return (Criteria) this;
		}

		public Criteria andLevelNotEqualTo(String value) {
			addCriterion("te.level <>", value, "level");
			return (Criteria) this;
		}

		public Criteria andLevelGreaterThan(String value) {
			addCriterion("te.level >", value, "level");
			return (Criteria) this;
		}

		public Criteria andLevelGreaterThanOrEqualTo(String value) {
			addCriterion("te.level >=", value, "level");
			return (Criteria) this;
		}

		public Criteria andLevelLessThan(String value) {
			addCriterion("te.level <", value, "level");
			return (Criteria) this;
		}

		public Criteria andLevelLessThanOrEqualTo(String value) {
			addCriterion("te.level <=", value, "level");
			return (Criteria) this;
		}

		public Criteria andLevelIn(List<String> values) {
			addCriterion("te.level in", values, "level");
			return (Criteria) this;
		}

		public Criteria andLevelNotIn(List<String> values) {
			addCriterion("te.level not in", values, "level");
			return (Criteria) this;
		}

		public Criteria andLevelBetween(String value1, String value2) {
			addCriterion("te.level between", value1, value2, "level");
			return (Criteria) this;
		}

		public Criteria andLevelNotBetween(String value1, String value2) {
			addCriterion("te.level not between", value1, value2, "level");
			return (Criteria) this;
		}
	}

	/**
	 * This class was generated by MyBatis Generator. This class corresponds to the database table t_exam
	 * @mbggenerated  Thu Sep 28 10:23:09 CST 2017
	 */
	public static class Criterion {
		private String condition;
		private Object value;
		private Object secondValue;
		private boolean noValue;
		private boolean singleValue;
		private boolean betweenValue;
		private boolean listValue;
		private String typeHandler;

		public String getCondition() {
			return condition;
		}

		public Object getValue() {
			return value;
		}

		public Object getSecondValue() {
			return secondValue;
		}

		public boolean isNoValue() {
			return noValue;
		}

		public boolean isSingleValue() {
			return singleValue;
		}

		public boolean isBetweenValue() {
			return betweenValue;
		}

		public boolean isListValue() {
			return listValue;
		}

		public String getTypeHandler() {
			return typeHandler;
		}

		protected Criterion(String condition) {
			super();
			this.condition = condition;
			this.typeHandler = null;
			this.noValue = true;
		}

		protected Criterion(String condition, Object value, String typeHandler) {
			super();
			this.condition = condition;
			this.value = value;
			this.typeHandler = typeHandler;
			if (value instanceof List<?>) {
				this.listValue = true;
			} else {
				this.singleValue = true;
			}
		}

		protected Criterion(String condition, Object value) {
			this(condition, value, null);
		}

		protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
			super();
			this.condition = condition;
			this.value = value;
			this.secondValue = secondValue;
			this.typeHandler = typeHandler;
			this.betweenValue = true;
		}

		protected Criterion(String condition, Object value, Object secondValue) {
			this(condition, value, secondValue, null);
		}
	}

	/**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table t_exam
     *
     * @mbggenerated do_not_delete_during_merge Tue Sep 19 17:54:16 CST 2017
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }
}